name: test
permissions:
  contents: read
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Go Version
        uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
        with:
          go-version: '1.23'
      - name: test
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/libs
          LITE_SERVERS: ${{ secrets.LITE_SERVERS }}
        run: |
          sudo apt-get install -y libsecp256k1-0
          mkdir -p ${{ env.LD_LIBRARY_PATH}}
          wget https://github.com/tonkeeper/tongo/raw/master/lib/linux/libemulator.so -O ${{ env.LD_LIBRARY_PATH}}/libemulator.so
          make test
